[users.jptiz]
shell = 'zsh'
groups = [
    'wheel',
    'audio',
]


[packages.pacman]
flags = "-S"
pkglist = [
    'ttf-fira-sans',
]


[packages.pikaur]
from-aur = true
flags = "-S"
pkglist = [
    'ttf-zilla-slab',
]
